---
name: Arduino_CI

on: [pull_request, push]

jobs:
  arduino_ci:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          arduino-platform: ["esp32"]

    steps:
      - uses: actions/checkout@v3
      - uses: Arduino-CI/action@stable-1.x # or latest, or a pinned version
        env:
            USE_SUBDIR: .
            EXPECT_EXAMPLES: true
            EXPECT_UNITTESTS: false
